src/carts/urls.py
from django.conf.urls import url
from .views import home, update, checkout

app_name = 'carts'
urlpatterns = [
    url(r'^$', home, name="index"),
    url(r'^update/$', update, name="update" ),
    url(r'^checkout/$', checkout, name="checkout" ),
]

src/comptes/urls.py
from django.conf.urls import url

from factures.views import UserFactureHistoryView
from .views         import ( UserDetailView, UsersDetailView, UserListView, UserEmailActivateView, UserDetailUpdateView, disable_enable_user )

app_name = 'comptes'
urlpatterns = [
    url(r'^$',                          UserDetailView.as_view(),           name='user_detail'),
    url(r'^details/(?P<pk>[\w.@+-]+)/$',UsersDetailView.as_view(), 			name="show" ),
    url(r'^list/$',                  	UserListView.as_view(),				name='user_list'),
    url(r'^details/$',                  UserDetailUpdateView.as_view(),     name='user-update'),
    url(r'history/factures/$',          UserFactureHistoryView.as_view(),   name='user-facture-history'),
    url(r'^email/resend-activation/$',  UserEmailActivateView.as_view(),  	name='resend-activation'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', UserEmailActivateView.as_view(),  name='email-activate'),
    url(r'^deu/(?P<pk>[\w.@+-]+)/$',			disable_enable_user,   					name='disable_enable' ),
]

# compte/email/confirm/asdfads/ -> activation view

src/fichiers/urls.py
from django.conf.urls import url
from .views import FichierListView, FichierDetailView, reglements, loaddt, test

app_name = 'fichiers'
urlpatterns = [
    url(r'^$',				FichierListView.as_view(), 		name="list" ),
    url(r'^reglement/$',	reglements,   					name='reglement' ),
    url(r'^load/$',			loaddt,   						name='load' ),
    url(r'^t/$',			test,   						name='test' ),
    url(r'^(?P<pk>\d+)/$',	FichierDetailView.as_view(),	name="show" ),
]

src/sbeeapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from .views import home_page, dash_page, contact_page
from comptes.views import LoginView, RegisterView

urlpatterns = [
    url(r'^$', home_page),
    url(r'^dashboard/$',    dash_page,      name='dash'),
    url(r'^contact/$',      contact_page,   name='contact'),
    url(r'^login/$',        LoginView.as_view(), name='login'),
    url(r'^logout/$',       LogoutView.as_view(),   name='logout'),
    url(r'^register/$',     RegisterView.as_view(), name='register'),
    
    url(r'^admin/',     admin.site.urls),
    url(r'^factures/',  include('factures.urls',    namespace='factures')),
    url(r'^fichiers/',  include('fichiers.urls',    namespace='fichiers')),
    url(r'^carts/',     include('carts.urls',       namespace='carts')),
    url(r'^compte/',    include('comptes.urls',     namespace='compte')),
    url(r'^comptes/',   include('comptes.passwords.urls', namespace='comptes')),
    url(r'^comptes/',   RedirectView.as_view(url='/compte')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns+static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

src/templates/base/breadcrumb.html
<!--   {% load static %}
  
  <section class="content-header">
    <h1>
      {% block page_title %}{% endblock page_title %}
      <small>{{request.get_full_path}}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#" class="disable">Un truc ici</a></li>
    </ol>
  </section> -->

src/templates/base/css.html
	{% load static %}
	<link rel="stylesheet" href='{% static "bower_components/bootstrap/dist/css/bootstrap.min.css" %}'>
	<link rel="stylesheet" href='{% static "bower_components/font-awesome/css/font-awesome.min.css" %}'>
	<link rel="stylesheet" href='{% static "bower_components/Ionicons/css/ionicons.min.css" %}'>
	<link rel="stylesheet" href='{% static "dist/css/AdminLTE.min.css" %}'>
	<link rel="stylesheet" href='{% static "dist/css/skins/_all-skins.min.css" %}'>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

src/templates/base/dashnav.html
		{% load static %}
		<aside class="main-sidebar">
	    <section class="sidebar">
	      <div class="user-panel">
	        <div class="pull-left image"><img src='{% static "dist/img/user2-160x160.jpg" %}' class="img-circle" alt="User Image"></div>
	        <div class="pull-left info">
	        	<p>{{request.user.nom}} {{request.user.prenoms}}</p>
	        	<a href="#"><i class="fa fa-circle text-success"></i> {{request.user.nom}}</a>
	        </div>
	      </div>
	      <ul class="sidebar-menu" data-widget="tree">
	        <li class="header">MENU</li>
<!-- 	        <li class=""><a href="{% url 'dash' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
 -->	        <li>
	          <a href="{% url 'factures:index' %}">
	            <i class="fa fa-file"></i> <span>Mes Factures</span>
	            <span class="pull-right-container"><small class="label pull-right bg-red">{{count}}</small></span>
	          </a>
	        </li>
	        <li><a href="#"><i class="fa fa-credit-card-alt"></i> <span>Paiements</span></a></li>
	        <li><a href='{% url "compte:user_detail" %}'><i class="fa fa-user"></i> <span>Mon compte</span></a></li>
	        {% if request.user.is_admin %}
	        <li><a href='{% url "compte:user_list" %}'><i class="fa fa-users"></i> <span>Utilisateurs</span></a></li>
	        <li><a href='{% url "fichiers:list" %}'><i class="fa fa-files-o"></i> <span>Fichiers</span></a></li>
	        {% endif %}
	        <li><a href='{% url "logout" %}'><i class="fa fa-sign-out"></i> <span>Deconnexion</span></a></li>
	      </ul>
	    </section>
	  </aside>

src/templates/base/footer.html
	{% load static %}
	<footer class="main-footer">
    <div class="pull-right hidden-xs"><b>Version</b> 1.0</div>
    <strong>Copyright &copy; 2018 <a href="https://sbee.bj" class="redhover">SBEE</a>.</strong>
  </footer>

  <aside class="control-sidebar control-sidebar-dark">
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs"></ul>
    <div class="tab-content"><div class="tab-pane" id="control-sidebar-home-tab"> </div> </div>
  </aside>
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

src/templates/base/js.html
	{% load static %}
	<script src='{% static "bower_components/jquery/dist/jquery.min.js" %}'></script>
	<script src='{% static "bower_components/bootstrap/dist/js/bootstrap.min.js" %}'></script>
	<script src='{% static "bower_components/jquery-slimscroll/jquery.slimscroll.min.js" %}'></script>
	<script src='{% static "bower_components/fastclick/lib/fastclick.js" %}'></script>
	<script src='{% static "dist/js/adminlte.min.js" %}'></script>
	<script src='{% static "dist/js/demo.js" %}'></script>

src/templates/base/navbar.html
  {% load static %}
  <header class="main-header">
    <a href="index2.html" class="logo">
      <span class="logo-mini">logo</span>
      <span class="logo-lg"><b>SBEE</b></span>
    </a>
    
    <nav class="navbar navbar-static-top">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i><span class="label label-success">0</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">Vous avez 0 messages</li>
<!--               <li>
                <ul class="menu">
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src='{% static "dist/img/user2-160x160.jpg" %}' class="img-circle" alt="User Image">
                      </div>
                      <h4>Support Team<small><i class="fa fa-clock-o"></i> 5 mins</small></h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                </ul>
              </li> 
              <li class="footer"><a href="#">See All Messages</a></li>
            -->
            </ul>
          </li>
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">{{count}}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">Vous avez {{count}} notifications</li>
<!--               <li>
                <ul class="menu">
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li> -->
            </ul>
          </li>
          <li class="dropdown tasks-menu">
            <a href='{% url "carts:index" %}'>
              Liste des factures choisies
              <i class="fa fa-shopping-cart"></i>
              <span class="label label-danger">{{ request.session.cart_items_count}}</span>
            </a>
          </li>
          <li class="dropdown user user-menu">
            <a href='{% url "compte:user_detail" %}' class="dropdown-toggle" data-toggle="dropdown">
              <img src='{% static "dist/img/user2-160x160.jpg" %}' class="user-image" alt="User Image">
              <span class="hidden-xs">{{request.user.nom}} {{request.user.prenoms}}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <img src='{% static "dist/img/user2-160x160.jpg" %}' class="img-circle" alt="User Image">

                <p>
                  {{request.user.nom}} {{request.user.prenoms}}
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a href='{% url "compte:user_detail" %}' class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href='{% url "logout" %}' class="btn btn-default btn-flat">Se Deconnecter</a>
                </div>
              </li>
            </ul>
          </li>
          <li><a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a></li>
        </ul>
      </div>
    </nav>
  </header>

src/templates/base/starter.html
{% extends "base.html" %}
{% load static %}



{% block morecss %}
    <link rel="stylesheet" href='{% static "bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}'>
{% endblock morecss %}


{% block content %}
  
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box"  style="padding: 20px">
            <div class="box-header">
              <h3 class="box-title">box_title</h3>
              <hr>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              page_content_goes_here
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
{% endblock content %}


{% block morejs %}
    <script src='{% static "bower_components/datatables.net/js/jquery.dataTables.min.js" %}'></script>
{% endblock morejs %}