src/carts/urls.py
from django.conf.urls import url
from .views import home, update, checkout

app_name = 'carts'
urlpatterns = [
    url(r'^$', home, name="index"),
    url(r'^update/$', update, name="update" ),
    url(r'^checkout/$', checkout, name="checkout" ),
]

src/comptes/passwords/urls.py
# accounts.passwords.urls.py 
from django.conf.urls       import url
from django.contrib.auth    import views as auth_views

app_name = 'comptes'
urlpatterns  = [
    url(r'^password/change/$',      auth_views.PasswordChangeView.as_view(),        name='password_change'),
    url(r'^password/change/done/$', auth_views.PasswordChangeDoneView.as_view(),    name='password_change_done'),
    url(r'^password/reset/$',       auth_views.PasswordResetView.as_view(),         name='password_reset'),
    url(r'^password/reset/done/$',  auth_views.PasswordResetDoneView.as_view(),     name='password_reset_done'),
    
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
            auth_views.PasswordResetConfirmView.as_view(),  name='password_reset_confirm'),

    url(r'^password/reset/complete/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

src/comptes/urls.py
from django.conf.urls import url

from factures.views import UserFactureHistoryView
from .views         import ( UserDetailView, UsersDetailView, UserListView, UserEmailActivateView, UserDetailUpdateView, disable_enable_user )

app_name = 'comptes'
urlpatterns = [
    url(r'^$',                          UserDetailView.as_view(),           name='user_detail'),
    url(r'^details/(?P<pk>[\w.@+-]+)/$',UsersDetailView.as_view(), 			name="show" ),
    url(r'^list/$',                  	UserListView.as_view(),				name='user_list'),
    url(r'^details/$',                  UserDetailUpdateView.as_view(),     name='user-update'),
    url(r'history/factures/$',          UserFactureHistoryView.as_view(),   name='user-facture-history'),
    url(r'^email/resend-activation/$',  UserEmailActivateView.as_view(),  	name='resend-activation'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', UserEmailActivateView.as_view(),  name='email-activate'),
    url(r'^deu/(?P<pk>[\w.@+-]+)/$',			disable_enable_user,   					name='disable_enable' ),
]

# compte/email/confirm/asdfads/ -> activation view

src/sbeeapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from .views import home_page, dash_page, contact_page
from comptes.views import LoginView, RegisterView

urlpatterns = [
    url(r'^$', home_page),
    url(r'^dashboard/$',    dash_page,      name='dash'),
    url(r'^contact/$',      contact_page,   name='contact'),
    url(r'^login/$',        LoginView.as_view(), name='login'),
    url(r'^logout/$',       LogoutView.as_view(),   name='logout'),
    url(r'^register/$',     RegisterView.as_view(), name='register'),
    
    url(r'^admin/',     admin.site.urls),
    url(r'^factures/',  include('factures.urls',    namespace='factures')),
    url(r'^fichiers/',  include('fichiers.urls',    namespace='fichiers')),
    url(r'^carts/',     include('carts.urls',       namespace='carts')),
    url(r'^compte/',    include('comptes.urls',     namespace='compte')),
    url(r'^comptes/',   include('comptes.passwords.urls', namespace='comptes')),
    url(r'^comptes/',   RedirectView.as_view(url='/compte')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns+static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

src/comptes/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth            import authenticate, login, get_user_model
from django.contrib.auth.models     import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins     import LoginRequiredMixin
from django.contrib                 import messages
from django.core.urlresolvers       import reverse
from django.utils.decorators        import method_decorator
from django.views.generic           import CreateView, FormView, DetailView, ListView, View, UpdateView
from django.views.generic.edit      import FormMixin
from django.http                    import HttpResponse, HttpResponseRedirect
from django.shortcuts               import render,redirect

from django.utils.http              import is_safe_url
from django.utils.safestring        import mark_safe
from rolepermissions.roles          import assign_role

from sbeeapp.mixins     import NextUrlMixin, RequestFormAttachMixin
from .forms             import LoginForm, RegisterForm, ReactivateEmailForm, UserDetailChangeForm
from .models            import User, EmailActivation
from .signals           import user_logged_in
from factures.models    import Facture

# def group_perm(request):
#     # creating the group
#     new_group, created = Group.objects.get_or_create(name ='Abonne')
#     # Code to add permission to group
#     ct = ContentType.objects.get_for_model(User)
     
#     # If I want to add 'Can go Haridwar' permission to level0 ?
#     ('VIEW_FILES', 'can view files and related stuff')
#     permission = Permission.objects.create(codename ='VIEW_FILES', name='Can view files and related stuff', content_type=ct)
#     new_group.permissions.add(permission)

#     new_group.user_set.add(request.user)




class UserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'comptes/details.html'

    def get_queryset(self, *args, **kwargs):
        impaye = Facture.objects.get(ref__exact=self.request.user.ref_abonne)
        context = { 'user' : self.request.user , 'impaye' : impaye}

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        impaye = Facture.objects.filter(ref__exact=self.request.user.ref_abonne)
        context = { 'user' : self.request.user , 'impaye' : impaye}
        print(context)
        return context




class UserListView(LoginRequiredMixin, ListView):
    queryset = User.objects.all()
    template_name = "comptes/list.html"



class UsersDetailView(LoginRequiredMixin, DetailView):
    queryset = User.objects.all()
    template_name = 'comptes/details.html'



class UserEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Votre compte a été activé. Vous pouvez desormais vous connecter")
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Votre compte a deja été activé. <a href="{link}">restaurer votre mot de passse</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login") 
        context = {'form': self.get_form(),'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        request = self.request
        messages.success(request, "Email d'Activation envoyé. Verifiez votre boite mail afin de proceder à l'activation de votre compte.")
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        assign_role(user, 'abonne')
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(UserEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key }
        return render(self.request, 'registration/activation-error.html', context)



class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/factures'
    template_name = 'auth/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)



class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'auth/register.html'
    success_url = '/login'



class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'comptes/update.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Changer les details de votre compte'
        return context

    def get_success_url(self):
        return reverse("compte:user_detail")

    
def disable_enable_user(request, pk):
    user = User.objects.get(pk = pk)
    if user.is_active :
        user.is_active = False
        messages.success(request, 'Compte de l\'utilisateur désactivé')
    else:
        user.is_active = True
        messages.success(request, 'Compte de l\'utilisateur activé')
    user.save()
    return redirect('compte:user_detail')

src/templates/comptes/details.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
    <link rel="stylesheet" href='{% static "bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}'>
{% endblock morecss %}

{% block content %}
	     
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box"  style="padding: 20px">
            <div class="box-header">
              <h3 class="box-title">Details du compte</h3>
            </div>
            <hr>
            <!-- /.box-header -->
            <div class="box-body">
              <dl>
                <dt class="col-xs-4" >Référence Abonne :</dt>
                <dd class="col-xs-8">{{ user.ref_abonne }}</dd>
                <dt class="col-xs-4" >Nom :</dt>
                <dd class="col-xs-8">{{ user.nom }}</dd>
                <dt class="col-xs-4" >Prenoms :</dt>
                <dd class="col-xs-8">{{ user.prenoms }}</dd>
                <dt class="col-xs-4" >Email :</dt>
                <dd class="col-xs-8">{{ user.email }}</dd>
                <dt class="col-xs-4" >Télephone :</dt>
                <dd class="col-xs-8">{% if user.telephone %}{{ user.telephone }}{% else %} Non defini
                    {% endif %}</dd>
              </dl>
            </div>
            <div class="box-footer">
              {% if request.user.ref_abonne == user.ref_abonne %}
                <a href='{% url "compte:user-update" %}' class="btn btn-primary pull-left"><i class="fa fa-pencil"></i> Modifier</a>
              {% endif %}
              {% if request.user.is_admin %}
              <form class="" method="post" action='{% url "compte:disable_enable" pk=user.pk %}'>
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{user.pk}}">
                <button class="btn btn-danger pull-right" type="submit"><i class="fa fa-lock"></i> 
                {% if user.is_active %}
                  Desactiver
                  {% else %}
                  Activate
                {% endif %}
                </button>
              </form>
              {% endif %}
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->

  
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box"  style="padding: 20px">
            <div class="box-header">
              <h3 class="box-title">Factures impayées</h3>
              <hr>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Référence</th>
                  <th>Période</th>
                  <th>Date Limite</th>
                  <th>Abonné</th>
                  <th>Montant</th>
                  <th>Options</th>
                </tr>
                </thead>
                <tbody>
                  {% for facture in impaye %}
                      <tr>
                      <td>{{ facture.ref }}</td>
                      <td>{{ facture.periode_factuu }} {{ facture.annee_factu }}</td>
                      <td>{{ facture.date_limitee }}</td>
                      <td>{{ facture.nom_abonne }}</td>
                      <td>{{ facture.montant_ttc }} FCFA</td>
                      <td class="text-center"><a type="button" href="{{facture.get_url}}" class="btn bg-olive">Voir</a></td>
                      </tr>
                  {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                  <th>Référence</th>
                  <th>Période</th>
                  <th>Date Limite</th>
                  <th>Abonné</th>
                  <th>Montant</th>
                  <th>Options</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
    
{% endblock content %}

{% block morejs %}
    <script src='{% static "bower_components/datatables.net/js/jquery.dataTables.min.js" %}'></script>
  	<script src='{% static "bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}'></script>
  	<script>
  	  $(function () {
  	    $('#example1').DataTable()
  	  })
  	</script>
{% endblock morejs %}

src/templates/comptes/list.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
  Factures    
{% endblock page_title %}

{% block morecss %}
    <link rel="stylesheet" href='{% static "bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}'>
{% endblock morecss %}

{% block content %}
  
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box"  style="padding: 20px">
            <div class="box-header">
              <h3 class="box-title">Administrateurs</h3>
              <hr>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Référence</th>
                  <th>Nom</th>
                  <th>Prénoms</th>
                  <th>Email</th>
                  <th>Activé</th>
                  <th>Options</th>
                </tr>
                </thead>
                <tbody>
                  {% for user in object_list %}
                  {% if user.is_admin == True %}
                    <tr>
                      <td>{{ user.ref_abonne }}</td>
                      <td>{{ user.nom }}</td>
                      <td>{{ user.prenoms }}</td>
                      <td>{{ user.email }}</td>
                      <td>{{ user.is_active }}</td>
                      <td class="text-center"><a type="button" href="{{user.get_url}}" class="btn bg-olive">Voir</a></td>
                    </tr>
                  {% endif %}
                  {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                  <th>Référence</th>
                  <th>Nom</th>
                  <th>Prénoms</th>
                  <th>Email</th>
                  <th>Activé</th>
                  <th>Options</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->

  
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box"  style="padding: 20px">
            <div class="box-header">
              <h3 class="box-title">Abonnés</h3>
              <hr>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Référence</th>
                  <th>Nom</th>
                  <th>Prénoms</th>
                  <th>Email</th>
                  <th>Activé</th>
                  <th>Options</th>
                </tr>
                </thead>
                <tbody>
                  {% for user in object_list %}
                  {% if user.is_admin == False %}
                    <tr>
                      <td>{{ user.ref_abonne }}</td>
                      <td>{{ user.nom }}</td>
                      <td>{{ user.prenoms }}</td>
                      <td>{{ user.email }}</td>
                      <td>{{ user.is_active }}</td>
                      <td class="text-center"><a type="button" href="{{user.get_url}}" class="btn bg-olive">Voir</a></td>
                    </tr>
                  {% endif %}
                  {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                  <th>Référence</th>
                  <th>Nom</th>
                  <th>Prénoms</th>
                  <th>Email</th>
                  <th>Activé</th>
                  <th>Options</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->    
{% endblock content %}

{% block morejs %}
    <script src='{% static "bower_components/datatables.net/js/jquery.dataTables.min.js" %}'></script>
	<script src='{% static "bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}'></script>
	<script>
	  $(function () {
	    $('#example1').DataTable()
	  })
	</script>
{% endblock morejs %}

src/templates/comptes/update.html
{% extends "base.html" %}

{% block content %}

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box"  style="padding: 20px">
            <div class="box-header">
				{% if title %}<h3 class='box-title my-3'>{{ title }}</h3>{% endif %}
            </div>
            <hr>
            <!-- /.box-header -->
            <div class="box-body">
				<div class='col-12 col-md-6 mx-auto'>
				<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}' id="form">
					{% csrf_token %}
				    {% if next_url %}
				    <input type='hidden' name='next' value='{{ next_url }}' />
				    {% endif %}
				  {{ form.as_p }}
				</form>
				</div>
            </div>
            <div class="box-footer">
              <button id='send' href='{% url "compte:user-update" %}' class="btn btn-danger pull-left"><i class="fa fa-pencil"></i> Modifier </button>
              <a onclick="history.back();" class="btn btn-primary pull-right"><i class="fa fa-times"></i> Annuler </a>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->

{% endblock %}

{% block morejs %}
    <script type="text/javascript">
    $( "#send" ).click(function() {
		$('#form').submit()
	});

    </script>
{% endblock morejs %}