src/carts/urls.py
from django.conf.urls import url
from .views import home, update, checkout

app_name = 'carts'
urlpatterns = [
    url(r'^$', home, name="index"),
    url(r'^update/$', update, name="update" ),
    url(r'^checkout/$', checkout, name="checkout" ),
]

src/factures/urls.py
from django.conf.urls import url
from .views import FactureListView, FactureDetailView

app_name = 'factures'
urlpatterns = [
    url(r'^$',             FactureListView.as_view(), 	name="index" ),
    url(r'^(?P<pk>\d+)/$', FactureDetailView.as_view(), name="show" ),
]

src/sbeeapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from .views import home_page, dash_page, contact_page
from comptes.views import LoginView, RegisterView

urlpatterns = [
    url(r'^$', home_page),
    url(r'^dashboard/$',    dash_page,      name='dash'),
    url(r'^contact/$',      contact_page,   name='contact'),
    url(r'^login/$',        LoginView.as_view(), name='login'),
    url(r'^logout/$',       LogoutView.as_view(),   name='logout'),
    url(r'^register/$',     RegisterView.as_view(), name='register'),
    
    url(r'^admin/',     admin.site.urls),
    url(r'^factures/',  include('factures.urls',    namespace='factures')),
    url(r'^fichiers/',  include('fichiers.urls',    namespace='fichiers')),
    url(r'^carts/',     include('carts.urls',       namespace='carts')),
    url(r'^compte/',    include('comptes.urls',     namespace='compte')),
    url(r'^comptes/',   include('comptes.passwords.urls', namespace='comptes')),
    url(r'^comptes/',   RedirectView.as_view(url='/compte')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns+static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

src/factures/models.py
from django.db import models
from django.urls import reverse
from comptes.models import User
from datetime import datetime

class FactureManager(models.Model):
	def get_by_id(self, id):
		return self.get_queryset().filter(id=id)

class ImpayeeManager(models.Manager):
	def get_queryset(self):
		return super(ImpayeeManager, self).get_queryset().filter(status='i')


class PayeeManager(models.Manager):
	def get_queryset(self):
		return super(PayeeManager, self).get_queryset().filter(status='p')



class Facture(models.Model):
	user_ref		= models.ForeignKey(User, null=True, related_name="user", verbose_name="Reference Abonne", on_delete=models.CASCADE)
	agence 			= models.IntegerField( help_text="AGENCE PAYEUR" , verbose_name="AGENCE PAYEUR"	)
	centre 			= models.IntegerField( help_text="CENTRE PAYEUR" , verbose_name="CENTRE PAYEUR"	)
	panneau 		= models.CharField(max_length=8, help_text="PANNEAU" , verbose_name="PANNEAU"	)
	ref 			= models.CharField(max_length=30, help_text="REFERENCE ABONNE" , verbose_name="REFERENCE ABONNE"	)
	annee_conso		= models.IntegerField( help_text="ANNEE DE CONSOMMATION" , verbose_name="ANNEE DE CONSOMMATION"	)
	periode_conso 	= models.IntegerField( help_text="PERIODE DE CONSOMMATION" , verbose_name="PERIODE DE CONSOMMATION"	)
	annee_factu		= models.IntegerField( help_text="ANNEE DE FACTURATION" , verbose_name="ANNEE DE FACTURATION"	)
	periode_factu 	= models.IntegerField( help_text="PERIODE DE FACTURATION" , verbose_name="PERIODE DE FACTURATION"	)
	montant_conso 	= models.IntegerField( help_text="MONTANT CONSOMMATION" , verbose_name="MONTANT CONSOMMATION"	)
	montant_ht 		= models.IntegerField( help_text="MONTANT HORS TAXE" , verbose_name="MONTANT HORS TAXE"	)
	nufmmr 			= models.CharField(max_length=12, help_text="digits(nufmmr)" , verbose_name="digits(nufmmr)"	)
	montant_surtaxe = models.IntegerField( help_text="MONTANT SURTAXE" , verbose_name="MONTANT SURTAXE"	)
	contribution	= models.IntegerField( help_text="CONTRIBUTION ELEC/RURALE" , verbose_name="CONTRIBUTION ELEC/RURALE"	)
	montant_ttc 	= models.IntegerField( help_text="MONTANT TTC" , verbose_name="MONTANT TTC"	)
	net_a_payer		= models.IntegerField( help_text="NET A PAYER" , verbose_name="NET A PAYER"	)
	piece_conso		= models.CharField(max_length=3, help_text="TYPE PIECE CONSOM." , verbose_name="TYPE PIECE CONSOM."	)
	taux_tva		= models.IntegerField( help_text="TAUX TVA" , verbose_name="TAUX TVA"	)
	montant_tva 	= models.IntegerField( help_text="MONTANT TVA" , verbose_name="MONTANT TVA"	)
	conso_facture	= models.IntegerField( help_text="Conso facturée" , verbose_name="Conso facturée"	)
	jours_conso		= models.IntegerField( help_text="NOMBRE JOURS CONSO" , verbose_name="NOMBRE JOURS CONSO"	)
	old_index 		= models.IntegerField( help_text="ANCIEN INDEX" , verbose_name="ANCIEN INDEX"	)
	new_index 		= models.IntegerField( help_text="NOUVEL INDEX" , verbose_name="NOUVEL INDEX"	)
	date_releve 	= models.IntegerField( help_text="DATE RELEVE" , verbose_name="DATE RELEVE"	)
	tarif 			= models.CharField(max_length=4, help_text="TARIF" , verbose_name="TARIF"	)
	date_limite 	= models.IntegerField( help_text="DATE LIMITE PAIEMENT" , verbose_name="DATE LIMITE PAIEMENT"	)
	nom_abonne 		= models.CharField(max_length=40, help_text="NOM DU PAYEUR" , verbose_name="NOM DU PAYEUR"	)
	adresse 		= models.CharField(max_length=40, help_text="ADRESSE 1" , verbose_name="ADRESSE 1"	)
	montant_lht 	= models.IntegerField( help_text="MONTANT LOCATION HT" , verbose_name="MONTANT LOCATION HT"	)
	montant_al 		= models.IntegerField( help_text="MONTANT AUTRES LOCATIONS" , verbose_name="MONTANT AUTRES LOCATIONS"	)
	status_choices 	= (('p', 'Paye'), ('i', 'Impaye'),)
	timestamp		= models.DateTimeField(auto_now_add=True)
	status = models.CharField(max_length=1, choices=status_choices, blank=False,default='i',help_text='Paye ou Impaye')


	objects = FactureManager()

	class Meta:
		ordering = ('-timestamp',)

	def get_url(self):
		return reverse('factures:show', kwargs={'pk': self.pk})

	@property
	def date_limitee(self):
		data = str(self.date_limite)
		data = data[6:8] + data[4:6] + data[0:4]
		data = datetime.strptime(data, '%d%m%Y')
		data = datetime.strftime(data, '%d %b %Y')
		print(data)
		return data

	@property
	def periode_factuu(self):
		data = str(self.periode_factu)
		data = datetime.strptime(data, '%m')
		data = datetime.strftime(data, '%b')
		print(data)
		return data
	
	@property
	def taxe_func(self):
		return self.montant_lht * 0.18	
	
	@property
	def montant_func(self):
		return self.montant_conso + self.montant_surtaxe + self.contribution

	
	def __str__(self):
		return self.ref

	def __unicode__(self):
		return self.ref

	def __iter__(self):
		return iter([self.ref, self.periode_factuu, self.montant_ttc])

src/factures/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from carts.models import Cart
from .models import Facture

from django.template import RequestContext

class FactureListView(LoginRequiredMixin, ListView):
	#queryset = Facture.objects.filter(user_ref__iexact=self.request.user.ref_abonne)
	template_name = "factures/list.html"

	def get_queryset(self, *args, **kwargs):
		request = Facture.objects.filter(ref__exact=self.request.user.ref_abonne)
		return request


class FactureDetailView(LoginRequiredMixin, DetailView):
	queryset = Facture.objects.all()
	template_name = "factures/details.html"

	def get_context_data(self, *arg, **kwargs):
		context = super(FactureDetailView, self).get_context_data(*arg, **kwargs)
		request = self.request
		cart_obj, new_obj = Cart.objects.new_or_get(request)
		context["cart"] = cart_obj
		return context


class UserFactureHistoryView(LoginRequiredMixin, ListView):
	template_name = "factures/user-history.html"
	def get_context_data(self, *args, **kwargs):
		context = super(UserFactureHistoryView, self).get_context_data(*args, **kwargs)
		cart_obj, new_obj = Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj
		return context

	def get_queryset(self, *args, **kwargs):
		request = self.request
		views = request.user.objectviewed_set.by_model(Facture, model_queryset=False)
		return views

src/templates/factures/list.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
  Factures    
{% endblock page_title %}

{% block morecss %}
    <link rel="stylesheet" href='{% static "bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}'>
{% endblock morecss %}

{% block content %}
	
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box"  style="padding: 20px">
            <div class="box-header">
              <h3 class="box-title">Ce tableau contient la liste de vos factures</h3>
              <hr>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Référence</th>
                  <th>Période</th>
                  <th>Date Limite</th>
                  <th>Abonné</th>
                  <th>Montant</th>
                  <th>Options</th>
                </tr>
                </thead>
                <tbody>
                	{% for facture in facture_list %}
	                <tr>
                    <td>{{ facture.ref }}</td>
                    <td>{{ facture.periode_factuu }} {{ facture.annee_factu }}</td>
                    <td>{{ facture.date_limitee }}</td>
                    <td>{{ facture.nom_abonne }}</td>
                    <td>{{ facture.montant_ttc }} FCFA</td>
	                  <td class="text-center"><a type="button" href="{{facture.get_url}}" class="btn bg-olive">Voir</a></td>
	                </tr>
                	{% endfor %}
                </tbody>
                <tfoot>
                <tr>
                  <th>Référence</th>
                  <th>Période</th>
                  <th>Date Limite</th>
                  <th>Abonné</th>
                  <th>Montant</th>
                  <th>Options</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
    
{% endblock content %}

{% block morejs %}
    <script src='{% static "bower_components/datatables.net/js/jquery.dataTables.min.js" %}'></script>
	<script src='{% static "bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}'></script>
	<script>
	  $(function () {
	    $('#example1').DataTable()
	  })
	</script>
{% endblock morejs %}