src/carts/urls.py
from django.conf.urls import url
from .views import home, update, checkout

app_name = 'carts'
urlpatterns = [
    url(r'^$', home, name="index"),
    url(r'^update/$', update, name="update" ),
    url(r'^checkout/$', checkout, name="checkout" ),
]

src/sbeeapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from .views import home_page, dash_page, contact_page
from comptes.views import LoginView, RegisterView

urlpatterns = [
    url(r'^$', home_page),
    url(r'^dashboard/$',    dash_page,      name='dash'),
    url(r'^contact/$',      contact_page,   name='contact'),
    url(r'^login/$',        LoginView.as_view(), name='login'),
    url(r'^logout/$',       LogoutView.as_view(),   name='logout'),
    url(r'^register/$',     RegisterView.as_view(), name='register'),
    
    url(r'^admin/',     admin.site.urls),
    url(r'^factures/',  include('factures.urls',    namespace='factures')),
    url(r'^fichiers/',  include('fichiers.urls',    namespace='fichiers')),
    url(r'^carts/',     include('carts.urls',       namespace='carts')),
    url(r'^compte/',    include('comptes.urls',     namespace='compte')),
    url(r'^comptes/',   include('comptes.passwords.urls', namespace='comptes')),
    url(r'^comptes/',   RedirectView.as_view(url='/compte')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns+static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

src/carts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from factures.models import Facture

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
	def new_or_get(self, request):
		cart_id = request.session.get('cart_id', None)
		qs = self.get_queryset().filter(id=cart_id)
		if qs.count() == 1:
			new_obj = False
			cart_obj = qs.first()
			if request.user.is_authenticated and cart_obj.user is None:
				cart_obj.user = request.user
				cart_obj.save()
		else:
			cart_obj = self.new(user=request.user)
			new_obj = True
			request.session['cart_id'] = cart_obj.id
		return cart_obj, new_obj

	def new(self, user=None):
		user_obj = None
		if user is not None:
			if user.is_authenticated:
				user_obj = user
		return self.model.objects.create(user=user_obj)

		
class Cart(models.Model):
	"""docstring for Cart"""
	user 		= models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	factures	= models.ManyToManyField(Facture, blank=True)#create empty cart
	total		= models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
	timestamp	= models.DateTimeField(auto_now_add=True)
	update		= models.DateTimeField(auto_now=True)
	objects 	= CartManager()

	def __str__(self):
		return str(self.id)


def pre_save_cart_receiver(sender, instance, action, *args, **kwargs):
	if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
		factures = instance.factures.all()
		total = 0
		for x in factures:
			total += x.net_a_payer
		instance.total = total
		instance.save()

m2m_changed.connect(pre_save_cart_receiver, sender=Cart.factures.through)

src/carts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts 	import render, redirect
from billing.models 	import BillingProfile
from comptes.forms 		import LoginForm
from orders.models 		import Order
from factures.models 	import Facture
from .models 			import Cart



@login_required()
def home(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	return render(request, "cart/index.html", {"cart": cart_obj})


@login_required()
def update(request):
	facture_id = request.POST.get('facture_id')
	if facture_id is not None:
		try:
			facture_obj = Facture.objects.get(id=facture_id)
		except Facture.DoesNotExist:
			print("Show message to user product is gone")
			return redirect("carts:index")

		cart_obj, new_obj = Cart.objects.new_or_get(request)

		if facture_obj in cart_obj.factures.all():
			cart_obj.factures.remove(facture_obj)
		else:
			cart_obj.factures.add(facture_obj)

		request.session['cart_items_count'] = cart_obj.factures.count()
		print(request.session['cart_items_count'])
	return redirect("carts:index")


@login_required()
def page(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.factures.count() == 0:
		return redirect("cart:home")

	billing_profile, billing_guest_profile_created = BillingProfile.objects.new_or_get(request)

	if billing_profile is not None:
		order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)

	context = {
		"order": order_obj,
		"billing_profile": billing_profile,
		# "login_form": login_form,
	}
	return render(request, 'cart/checkout.html', context)


@login_required()
def checkout(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.factures.count() == 0:
		return redirect("cart:home")

	print(cart_obj.factures)


	billing_profile, billing_guest_profile_created = BillingProfile.objects.new_or_get(request)

	if billing_profile is not None:
		order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)

	context = {
		"order": order_obj,
		"billing_profile": billing_profile,
		# "login_form": login_form,
	}
	return render(request, 'cart/checkout.html', context)

src/templates/cart/checkout.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
    <link rel="stylesheet" href='{% static "bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}'>
{% endblock morecss %}

{% block content %}
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box"  style="padding: 20px">
              <div class="box-header">

              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <div class="col-xs-6">Total: </div><div class="col-xs-6">{{ order.cart.total }}</div>
                <div class="col-xs-6">Order Total: </div><div class="col-xs-6">{{ order.total }}</div>
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
{% endblock content %}

{% block morejs %}
    <script src='{% static "bower_components/datatables.net/js/jquery.dataTables.min.js" %}'></script>
  <script src='{% static "bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}'></script>
  <script>
    $(function () {
      $('#example1').DataTable()
    })
  </script>
{% endblock morejs %}

src/templates/cart/index.html
{% extends "base.html" %}
{% load static %}

{% block morecss %}
    <link rel="stylesheet" href='{% static "bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}'>
{% endblock morecss %}

{% block content %}

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box"  style="padding: 20px">
            <div class="box-header">
              <h3 class="box-title">Ce tableau contient la liste des factures sélectionnées</h3>
              <b class="pull-right">Total: {{ cart.total }} FCFA</b>
              <hr>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              {% if cart.factures.exists %}
              <table id="example1" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Référence</th>
                  <th>Période</th>
                  <th>Date Limite</th>
                  <th>Montant</th>
                  <th>Options</th>
                </tr>
                </thead>
                <tbody>
                  {% for facture in cart.factures.all %}
                  <tr>
                    <td>{{ facture.ref }}</td>
                    <td>{{ facture.periode_factuu }} {{ facture.annee_factu }}</td>
                    <td>{{ facture.date_limitee }}</td>
                    <td>{{ facture.montant_ttc }} FCFA</td>
                    <td class="btn-group col">
                      <div class="col-xs-5"><a type="button" href="{{facture.get_url}}" class="btn btn-success">Voir</a></div>
                      <div class="col-xs-7">{% include 'snippets/updatecart.html' with facture=facture cart=cart in_cart=True %}</div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                  <th>Référence</th>
                  <th>Période</th>
                  <th>Date Limite</th>
                  <th>Montant</th>
                  <th>Options</th>
                </tr>
                </tfoot>
              </table>
              <hr>
              <div>
                <div><button class="btn btn-success bn-lg col-xs-12 col-md-8 col-md-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4" data-toggle="modal" data-target="#myModal">Payer</button></div>
                <!-- <div><a href='{% url "carts:checkout" %}' class="btn btn-success bn-lg col-xs-12 col-md-8 col-md-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">Checkout</a></div> -->
              </div>
              {% else %}
                  <p class="text-center">Aucune facture choisie</p>
              {% endif %}

              <div class="modalss">

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Choississez votre methode de paiement</h4>
                      </div>
                      <div class="modal-body">

                        <div role="tabpanel">

                          <!-- Nav tabs -->
                          <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Mobile Money</a></li>
                            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Paypal</a></li>
                          </ul>

                          <!-- Tab panes -->
                          <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">
                              <div class="row" style="margin-top: 20px">
                                <div class="col-md-5"><img src='{% static "dist/img/mtn.jpg" %}' class="ing-responsive" height="150px;" alt="logo Mobile Money"></div>
                                <div class="col-md-7">
                                  <form class="" method="">
                                    <div class="form-group">
                                      <label for="exampleInputAmount">Entrez votre numéro de téléphone</label><br><br>
                                      <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                                        <input type="number" class="form-control" id="exampleInputAmount" placeholder="Numéro Mobile Money">
                                      </div>
                                    </div>
                                    <!-- <button type="submit" class="btn btn-primary text-center">Payer</button> -->
                                  </form>
                                  <div><a href='{% url "carts:checkout" %}' class="btn btn-success bn-lg col-xs-12 col-md-8 col-md-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">Payer</a></div>
                                </div>
                              </div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="profile">
                              <div class="row" style="margin-top: 20px">
                                <div class="col-md-5"><img src='{% static "dist/img/paypal.png" %}' class="ing-responsive" height="150px;" alt="logo Paypal"></div>
                                <div class="col-md-7">
                                  <form class="" method="">
                                    <div class="form-group">
                                      <label for="exampleInputAmount">Entrez votre adresse email</label><br><br>
                                      <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                                        <input type="email" class="form-control" id="exampleInputAmount" placeholder="Adresse Email Paypal">
                                      </div>
                                    </div>
                                    <!-- <button type="submit" class="btn btn-primary text-center">Payer</button> -->
                                  </form>
                                  <div><a href='{% url "carts:checkout" %}' class="btn btn-success bn-lg col-xs-12 col-md-8 col-md-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">Payer</a></div>
                                </div>
                              </div>
                            </div>
                          </div>

                        </div>


                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>


            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
{% endblock content %}

{% block morejs %}
    <script src='{% static "bower_components/datatables.net/js/jquery.dataTables.min.js" %}'></script>
  <script src='{% static "bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}'></script>
  <script>
    $(function () {
      $('#example1').DataTable()
    })
  </script>
{% endblock morejs %}